# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  # Manual invocation.
  workflow_dispatch:

  push:

jobs:
  CI:
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by guardian/actions-assume-aws-role
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/guardian/actions-assume-aws-role
      - uses: guardian/actions-assume-aws-role@v1
        with:
          awsRoleToAssume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      # Setup Node, checking common Node config files to determine the version of Node to use.
      # See https://github.com/guardian/actions-setup-node
      - name: Setup Node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: "yarn"

      - name: install dependencies
        run: yarn install

      - name: check for duplicate dependencies (if it fails here, then pre-commit hook is not working)
        run: yarn yarn-deduplicate --fail

      - name: generate TS definitions for GraphQL schema
        run: yarn graphql-refresh

      - name: perform a prettier check
        run: yarn prettier-check

      - name: perform a linting check
        run: yarn lint

      - name: write the current GIT hash to GIT_COMMIT_HASH.ts (so it's available at build time - so it gets baked into the artifact)
        run: |
          GIT_COMMIT_HASH=$(git rev-parse HEAD)
          echo 'export const GIT_COMMIT_HASH = "'$GIT_COMMIT_HASH'";' > GIT_COMMIT_HASH.ts

      - name: build all workspaces (i.e. modules)
        run: yarn build

      - name: combine client and bootstrapping-lambda into directory
        run: |
          mkdir -p dist/client
          cp -v bootstrapping-lambda/dist/index.js dist/
          cp -v client/dist/pinboard.main* dist/client
          cp -rv client/dist/push-notifications dist/client

      - name: upload riff-raff artifacts
        run: |
          LAST_TEAMCITY_BUILD=650
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          yarn node-riffraff-artifact
