# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  # Manual invocation.
  workflow_dispatch:

  push:

jobs:
  CI:
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by guardian/actions-assume-aws-role
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/guardian/actions-assume-aws-role
      - uses: guardian/actions-assume-aws-role@v1
        with:
          awsRoleToAssume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      # Setup Node, checking common Node config files to determine the version of Node to use.
      # See https://github.com/guardian/actions-setup-node
      - name: Setup Node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: "yarn"

      - name: Run script/ci
        run: |
          LAST_TEAMCITY_BUILD=650
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          ./scripts/ci.sh
